services:
  db:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  api:
    image: todo-backend
    container_name: todo-api
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb://db:27017/todoapp
      PORT: 3000
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: todo-frontend
    container_name: todo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mongo_data:
